repos:

# autoflake
-   repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args: [--in-place, --remove-all-unused-imports]

# isort
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--settings-path=pyproject.toml]

# black
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      args: [--config=pyproject.toml]
